name: Branch Delete Workflow

on:
  workflow_run:
    workflows:
      - 'Main Workflow'
    types:
      - completed

jobs:
  branch_delete_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check if Workflow Run is Deleted
        run: |
          if [ "${{ github.event_name }}" == "workflow_run" ] && [ "${{ github.event.action }}" == "completed" ]; then
            echo "Branch deleted. Run your specific steps here."
            # Add your steps to handle branch deletion
          else
            echo "No branch deletion event detected. Skipping steps."
          fi
