name: Branch Create Workflow

on:
  workflow_run:
    workflows:
      - 'Main Workflow'
    types:
      - completed

jobs:
  branch_create_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check if Workflow Run is Requested
        run: |
          if [ "${{ github.event_name }}" == "workflow_run" ] && [ "${{ github.event.action }}" == "requested" ]; then
            echo "Branch created. Run your specific steps here."
            # Add your steps to handle branch creation
          else
            echo "No branch creation event detected. Skipping steps."
          fi
