name: Branch Delete Workflow

on:
  workflow_run:
    workflows:
      - 'Main Workflow'
    types:
      - deleted

jobs:
  branch_delete_job:
    runs-on: ubuntu-latest

    steps:
      - name: Handle Branch Deletion
        run: |
          echo "Branch deleted. Run your specific steps here."
          # Add your steps to handle branch deletion
