name: Extended Workflow with Manual Approval

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  check_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run if branch is 'main'
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "This code will run only if the branch is 'main'"
          # Your specific steps for the 'main' branch

  manual_approval:
    runs-on: ubuntu-latest
    needs: check_branch
    steps:
      - name: Manual Approval
        if: github.event_name == 'workflow_dispatch'
        run: echo "Please approve this workflow run"

  execute_after_approval:
    runs-on: ubuntu-latest
    needs: manual_approval
    steps:
      - name: Execute steps after manual approval
        run: |
          echo "Steps after manual approval"
          # Your specific steps to be executed after manual approval
