name: Conditional Workflow

on:
  push:
    branches:
      - '*'

jobs:
  check_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run if branch is 'main'
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "This code will run only if the branch is 'main'"
          # Your specific steps for the 'main' branch

      - name: Run if branch is not 'main'
        if: ${{ github.ref != 'refs/heads/main' }}
        run: |
          echo "This code will run for branches other than 'main'"
          # Your specific steps for branches other than 'main'