name: Main Workflow

on:
  push:
    branches:
      - '*'
  pull_request:
  delete:
  create:
  workflow_run:
    workflows:
      - 'Branch Delete Workflow'
      - 'Branch Create Workflow'
    types:
      - requested

jobs:
  main_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your main workflow steps here